spring.application.name=sool
spring.profiles.active=dev

#Mybatis
mybatis.mapper-locations=classpath:/mapper/**/*.xml
mybatis.type-aliases-package=com.example.sool.dto
mybatis.configuration.map-underscore-to-camel-case=true

# email auth
app.email.auth.code-expire-seconds=300
app.email.auth.resend-wait-seconds=30
app.email.auth.max-fail-count=5

spring.config.additional-location=file:/app/config/